[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
CORS_ORIGINS = "https://dev-diligence-production.up.railway.app"
PORT = "8000"