[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "python -c \"import os; port = int(os.getenv('PORT', '8000')); import uvicorn; uvicorn.run('main:app', host='0.0.0.0', port=port, workers=1, timeout_keep_alive=75)\""

startupProbe = {
    path = "/health",
    initialDelaySeconds = 10,
    periodSeconds = 5,
    timeoutSeconds = 3,
    failureThreshold = 3
}

[variables]
CORS_ORIGINS = "https://dev-diligence-production.up.railway.app"
NEXT_PUBLIC_API_URL = "https://dev-diligence-production.up.railway.app"
