[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
startCommand = "sh -c 'uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug'"

[variables]
CORS_ORIGINS = "*"